# Use root/example as user/password credentials
version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'ContentCachingMech'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  redis-data: